# file: .gitpod.yml

image:
  file: .gitpod.Dockerfile

tasks:
  - command: 'hugo server --baseUrl $(gp url 1313) --appendPort=false --liveReloadPort 443'

ports:
  - port: 1313
    onOpen: ignore
  
  - port: 443
    onOpen: ignore
