
image:
  file: .gitpod.Dockerfile

tasks:
# TODO make live reload work
  - command: 'hugo server --baseUrl $(gp url 1313) --appendPort=false --disableLiveReload'

ports:
  - port: 1313
    onOpen: ignore

  - port: 443
    onOpen: ignore

vscode:
  extensions:
    - budparr.language-hugo-vscode
    - davidanson.vscode-markdownlint
