baseURL = "https://BrickSim.org"
languageCode = "en-us"
title = "BrickSim"
theme = "compose"
publishDir = "../BrickSim/docs"

enableGitInfo = true

##disableKinds = ["taxonomy", "taxonomyTerm"]

#  menu items
[[menu.main]]
    name = "Docs"
    weight = 2
    url = "docs/"

[[menu.main]]
    name = "Screenshots"
    weight = 3
    url = "screenshots/"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
        [markup.goldmark.extensions]
            typographer = false
    [markup.highlight]
        codeFences = true
        guessSyntax = false
        hl_Lines = ""
        lineNoStart = 1
        lineNos = true
        lineNumbersInTable = true
        noClasses = false
        style = "monokai"
        tabWidth = 2
    [markup.tableOfContents]
        endLevel = 4
        ordered = false
        startLevel = 2

# Everything below this are Site Params
[params]
    #todo custom_css = ["css/style.css"]

    repo = "https://github.com/bb1950328/BrickSim"

    time_format_blog = "Monday, January 02, 2006"
    time_format_default = "January 2, 2006"
    enableDarkMode = true
    codeLineNumbers = true

    [params.logo]
        lightMode = "img/logo.png"
        darkMode = "img/logo.png"

    [params.source]
        name = "GitHub"
        iconLight = "img/GitHubMarkLight.svg"
        iconDark = "img/GitHubMarkDark.svg"
        url = "https://github.com/bb1950328/BrickSim"