baseURL = "https://BrickSim.org"
languageCode = "en-us"
title = "BrickSim"
theme = "compose"
publishDir = "../BrickSim/docs"

enableGitInfo = true

##disableKinds = ["taxonomy", "taxonomyTerm"]

#  menu items
[[menu.main]]
    name = "Docs"
    weight = 2
    url = "docs/"

[[menu.main]]
    name = "Screenshots"
    weight = 3
    url = "screenshots/"

[outputs]
    home = ["HTML", "RSS","JSON"]

[frontmatter]
    lastmod = ["lastmod", ":git", "date", "publishDate"]

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
        [markup.goldmark.extensions]
            typographer = false
    [markup.highlight]
        codeFences = true
        guessSyntax = false
        hl_Lines = ""
        lineNoStart = 1
        lineNos = true
        lineNumbersInTable = true
        noClasses = false
        style = "monokai"
        tabWidth = 2
    [markup.tableOfContents]
        endLevel = 4
        ordered = false
        startLevel = 2

# Everything below this are Site Params
[params]
    repo = "https://github.com/bb1950328/BrickSim"

    uniqueHomePage = true

    time_format_blog = "Monday, January 02, 2006"
    time_format_default = "January 2, 2006"
    enableDarkMode = true
    codeLineNumbers = true

    [params.author]
        name = "bb1950328"
        url = "https://github.com/bb1950328"

    description = "BrickSim is an LDraw-based open source application to build and analyze LEGO® models on your computer."
    metaThemeColor = "#0155d9"

    [params.logo]
        lightMode = "img/logo.png"
        darkMode = "img/logo.png"

    [params.source]
        name = "GitHub"
        iconLight = "img/GitHubMarkLight.svg"
        iconDark = "img/GitHubMarkDark.svg"
        url = "https://github.com/bb1950328/BrickSim"

[sitemap]
    changefreq = 'weekly'
    filename = 'sitemap.xml'
    priority = 0.5