# This is a basic workflow to help you get started with Actions

name: Hugo Static Site Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: clone bb1950328/BrickSim.git
        run: |
          mkdir $GITHUB_WORKSPACE/BrickSim
          cd $GITHUB_WORKSPACE/BrickSim
          git init
          git pull https://${{ secrets.BRICKSIM_TOKEN }}:x-oauth-basic@github.com/bb1950328/BrickSim.git --ff-only
      - name: clone bb1950328/BrickSimWeb.git
        run: |
          mkdir $GITHUB_WORKSPACE/BrickSimWeb
          cd $GITHUB_WORKSPACE/BrickSimWeb
          git init
          git pull https://${{ secrets.BRICKSIM_TOKEN }}:x-oauth-basic@github.com/bb1950328/BrickSimWeb.git --ff-only
          git submodule update --init --recursive
      
      - run: ls -l -R $GITHUB_WORKSPACE
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.0'
          extended: true

      - name: Build
        run: |
          cd $GITHUB_WORKSPACE/BrickSimWeb
          hugo --minify

      - name: Configure git user
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Actions Bot"
      
      - name: Commit changes
        run: |
          cd $GITHUB_WORKSPACE/BrickSim/
          git add docs/*
          git commit -m "Update Website from bb1950328/BrickSimWeb"

      - name: Push changes
        run: git push
